global using static WarhammerCombatMathLibrary.CombatMath.Utilities;
global using static WarhammerCombatMathLibrary.CombatMath.Helpers;
global using static WarhammerCombatMathLibrary.CombatMath.Constants;